### ISSUE TITLE
Feature request: Adding timestamps to the output?

### ISSUE THREAD

**Issue by wilk-polarny** [dashpay/sentinel#10]
Hi,

it would be nice to have some timestamps on the output generated by sentinel. I'm writing output to a local log file for automated analysis and rotation, therfore it would be nice to have a date/time stamp. Even better, configurable ones using a customizable time format string.

**Comment by nmarley** [comment]
If you set the SENTINEL_DEBUG environment variable, you get logs with timestamps as defined here: https://github.com/dashpay/sentinel/blob/master/lib/misc.py#L22-L27

Any output that comes from sentinel when that variable is _not_ set is probably some kind of warning/error intended for the operator to see and take action on, e.g. JSONRPC misconfiguration or invalid masternode status message.

Do you have a specific example of a message from sentinel that you would prefer had a timestamp?

**Comment by taw00** [comment]
I files something similar to this a long time ago.

A warning / error intended for the operator: That operator 9 times out of 10 is seeing that message via a log  populated by crontab. If you don't see it for some time, the error loses meaning very quickly.

I get around this by timestamping every single sentinel run through crontab magic, but that is less than ideal because most runs log nothing.

This is a system application, not a command-line utility. It needs to timestamp the output by default or via some option in config or some such.

**Comment by thephez** [comment]
Closing this issue since Dash Core v20 integrated all Sentinel functionality and [rendered Sentinel obsolete](https://github.com/dashpay/dash/blob/v20.0.0/doc/release-notes.md#sentinel-deprecation).

**Comment by thephez** [comment]
Closing this issue since Dash Core v20 integrated all Sentinel functionality and [rendered Sentinel obsolete](https://github.com/dashpay/dash/blob/v20.0.0/doc/release-notes.md#sentinel-deprecation).
